# SPDX-FileCopyrightText: 2022 Alec Delaney for Adafruit Industries
#
# SPDX-License-Identifier: MIT

[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools-scm",
]

[project]
name = "adafruit-circuitpython-ina219"
description = "CircuitPython library for INA219 high side DC current sensor."
version = "0.0.0+auto.0"
readme = "README.rst"
authors = [
    {name = "Adafruit Industries", email = "circuitpython@adafruit.com"}
]
urls = {Homepage = "https://github.com/adafruit/Adafruit_CircuitPython_INA219"}
keywords = [
    "adafruit",
    "blinka",
    "circuitpython",
    "micropython",
    "ina219",
    "sensor",
    "current",
    "high",
    "voltage",
    "featherwing",
    "breakout",
    "hardware",
]
license = {text = "MIT"}
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Embedded Systems",
    "Topic :: System :: Hardware",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
dynamic = ["dependencies"]

[tool.setuptools]
py-modules = ["adafruit_ina219"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
