OLED_ENABLE = yes
OLED_TRANSPORT = i2c
OLED_DRIVER = ssd1306

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes

SRC += matrix.c
CUSTOM_MATRIX = yes
MIDI_ENABLE = yes
UNICODE_ENABLE = yes
REPEAT_KEY_ENABLE = yes
I2C_DRIVER_REQUIRED = yes
