# SPDX-FileCopyrightText: 2022 Alec Delaney for Adafruit Industries
#
# SPDX-License-Identifier: MIT

[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools-scm",
]

[project]
name = "adafruit-circuitpython-veml7700"
description = "CircuitPython driver for VEML7700 high precision I2C ambient light sensor."
version = "0.0.0+auto.0"
readme = "README.rst"
authors = [
    {name = "Adafruit Industries", email = "circuitpython@adafruit.com"}
]
urls = {Homepage = "https://github.com/adafruit/Adafruit_CircuitPython_VEML7700"}
keywords = [
    "adafruit",
    "blinka",
    "circuitpython",
    "micropython",
    "veml7700",
    "ambient",
    "light",
    "sensor",
    "i2c",
    "precision",
]
license = {text = "MIT"}
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Embedded Systems",
    "Topic :: System :: Hardware",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
dynamic = ["dependencies"]

[tool.setuptools]
py-modules = ["adafruit_veml7700"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
