// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define ENCODER_A_PINS { GP27, GP28 }
#define ENCODER_B_PINS { GP29, GP6 }
#define ENCODER_C_PINS { GP7, GP0 }

#define KEY_1 KC_LEFT
#define KEY_2 KC_DOWN
#define KEY_3 KC_UP
#define KEY_4 KC_RIGHT

#define WS2812_DI_PIN GP26
#define RGBLIGHT_LED_COUNT 4

#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING

#define RGBLIGHT_HUE_STEP 10
#define RGBLIGHT_SAT_STEP 17
#define RGBLIGHT_VAL_STEP 17