#define OLED_TIMEOUT 15000
#define OLED_FADE_OUT 1

#define WS2812_DI_PIN GP3
#define RGBLIGHT_LED_COUNT 4
#define RGBLIGHT_MAX_LAYERS 1

#define WPM_UNFILTERED 1
#define WPM_ESTIMATED_WORD_SIZE 1 // KPS
#define WPM_SAMPLE_SECONDS 1

// Free up space
#undef RGBLIGHT_ANIMATIONS
#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_EFFECT_TWINKLE