M48
; DRILL file {KiCad 7.0.10} date Monday, February 10, 2025 at 10:38:25 AM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-10T10:38:25-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X136.34Y-116.429
X136.34Y-126.589
X156.54Y-116.429
X156.54Y-126.589
T2
X136.34Y-121.509
X156.54Y-121.509
M30
