#define ENCODER_A_PINS { GP10 }
#define ENCODER_B_PINS { GP9 }

#define WS2812_DI_PIN GP8
#define RGBLIGHT_LED_COUNT 6

#define BOOTMAGIC_ROW 3
#define BOOTMAGIC_COLUMN 1

#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_BREATHING	
#define RGBLIGHT_EFFECT_CHRISTMAS	
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_TWINKLE
