#define MATRIX_COLS 3
#define MATRIX_ROWS 3
#define MATRIX_COL_PINS { GP28, GP27, GP26 }
#define MATRIX_ROW_PINS { GP1, GP2, GP4 }

#define ENCODER_A_PINS { GP0 }
#define ENCODER_B_PINS { GP29 }
#define ENCODER_S1_PIN  GP3 

#define OLED_I2C_SCL_PIN GP7
#define OLED_I2C_SDA_PIN GP6

#define OLED_DRIVER_ENABLE
#define ROTARY_ENCODER_ENABLE
