// config.h
#pragma once

#define MATRIX_ROWS 4
#define MATRIX_COLS 3

#define MATRIX_ROW_PINS { GP0, GP1, GP2, GP3 }
#define MATRIX_COL_PINS { GP4, GP5, GP6 }

#define DIODE_DIRECTION COL2ROW

#define WS2812_DI_PIN GP7
#define RGB_MATRIX_LED_COUNT 12
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP8
#define I2C1_SCL_PIN GP9

#define OLED_DISPLAY_128X64
#define OLED_TIMEOUT 60000

#define RP2040_FLASH_GENERIC_03H
#define RP2040_FLASH_SIZE_16M_BYTES