#define ENCODER_A_PINS { GP2 }
#define ENCODER_B_PINS { GP4 }
/* REMOVED RGB LIGHTING
#define WS2812_DI_PIN GP26
#define RGBLIGHT_LED_COUNT 1
#define RGBLIGHT_DEFAULT_HUE 190
#define RGBLIGHT_DEFAULT_SAT 128
#define RGBLIGHT_LAYERS
*/
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7